config/routes.rb
Rails.application.routes.draw do
  resources:employers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer.rb
class Employer < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :phone_number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
    def index
        @employers = Employer.all
    end
    def show
        @employer = Employer.find(params[:id])
    end

    def destroy
        @employer = Employer.find(params[:id])
        @employer.destroy

        redirect_to employers_path
    end

    def new
        @employer = Employer.new
    end

    def create
        @employer = Employer.new(employer_params)
        if @employer.save
            redirect_to employers_path
          else
            render 'new'
          end
    end

    def edit
      @employer = Employer.find(params[:id])
    end

    def update
      @employer = Employer.find(params[:id])

      if @employer.update(employer_params)
        redirect_to employers_path
      else
        render 'edit'
      end
    end

    private

    def employer_params
        params.require(:employer).permit(:name, :email, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/edit.html.erb
<h2>Update Employer</h2>

<%= form_for :employer, url: employer_path(@employer), method: :patch do |f| %>
  <p>
    <%= f.label :companyname %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
      <%= f.label :Phonenumber %><br>
      <%= f.text_field :phone_number %>
    </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/employers/index.html.erb
<h2>Employers:</h2>
<%= link_to 'New Employer', new_employer_path %>
<table style="width:100%">
  	<tr>
	    <th>Company Name</th>
	    <th>Email</th>
	    <th>Phone Number</th>
	    <th>Actions</th>
  	</tr>
  	<% @employers.each do |employer| %>
  	<tr>
	    <td><%= employer.name%></td>
	    <td><%= employer.email%></td>
	    <td><%= employer.phone_number%></td>
	    <td><%= link_to 'Show', employer_path(employer)  %></td>
	    <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
	    <td><%= link_to 'Delete', employer_path(employer), method: :delete, data: { confirm: 'Are you sure you want to delete this employer?' } %></td>
  	</tr>
  	<% end %>
</table>

app/views/employers/new.html.erb
<h2>Add Employer</h2>

<%= form_for :employer, url: employers_path do |f| %>
    <% if @employer.errors.any? %>
        <div id="error_explanation">
          	<h2>
            	<%= pluralize(@employer.errors.count, "error") %> prohibited
            	this employer from being saved:
          	</h2>
          	<ul>
            	<% @employer.errors.full_messages.each do |msg| %>
             	 <li><%= msg %></li>
            	<% end %>
          	</ul>
        </div>
      <% end %>
    <p>
        <%= f.label :companyname %><br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </p>
    <p>
        <%= f.label :Phonenumber %><br>
        <%= f.text_field :phone_number %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/employers/show.html.erb
<p>
  <strong>Company Name:</strong>
  <%= @employer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employer.email %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @employer.phone_number %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>